# Завдання 4

In [ ]:
import numpy as np
import pandas as pd

array = np.random.random((10, 10))
min_index = np.unravel_index(np.argmin(array), array.shape)
max_index = np.unravel_index(np.argmax(array), array.shape)

display(pd.DataFrame(array))
display(pd.DataFrame({
    "Елемент": ["Мінімальний", "Максимальний"],
    "Значення": [np.min(array), np.max(array)],
    "Індекс (рядок, стовпець)": [min_index, max_index],
}))

,0,1,2,3,4,5,6,7,8,9
0,0.701481,0.447405,0.992598,0.934941,0.364710,0.929930,0.599743,0.685244,0.346000,0.740833
1,0.220861,0.041644,0.555596,0.389448,0.693287,0.114485,0.092256,0.536823,0.170377,0.776498
2,0.530626,0.755085,0.712039,0.545430,0.395168,0.923432,0.327005,0.504586,0.265901,0.467440
3,0.048455,0.690592,0.275019,0.675743,0.261467,0.725004,0.889772,0.796441,0.157187,0.634401
4,0.908964,0.628944,0.989386,0.604491,0.199639,0.234732,0.522634,0.717880,0.844184,0.270853
5,0.039908,0.465719,0.295772,0.755369,0.498112,0.462088,0.420737,0.323503,0.600574,0.149354
6,0.883385,0.157865,0.934812,0.674350,0.399053,0.683380,0.287240,0.728248,0.864161,0.535276
7,0.600864,0.735699,0.515542,0.801733,0.698374,0.023607,0.749841,0.518831,0.321083,0.258138
8,0.000578,0.226308,0.964257,0.790537,0.201799,0.889441,0.943384,0.548746,0.818772,0.894871
9,0.105623,0.672663,0.201700,0.843092,0.553222,0.401209,0.807318,0.624645,0.799412,0.504030

        Елемент  Значення Індекс (рядок, стовпець)
0   Мінімальний  0.000578                   (8, 0)
1  Максимальний  0.992598                   (0, 2)