# Завдання 2

In [ ]:
import numpy as np
import pandas as pd

array = np.random.randint(1, 51, size=(4, 4))

display(pd.DataFrame(array, index=["Рядок 1", "Рядок 2", "Рядок 3", "Рядок 4"],
                     columns=["Стовпець 1", "Стовпець 2", "Стовпець 3", "Стовпець 4"]))

row_sums = np.sum(array, axis=1)
column_sums = np.sum(array, axis=0)

display(pd.DataFrame({"Рядок": [1, 2, 3, 4], "Сума": row_sums}))
display(pd.DataFrame({"Стовпець": [1, 2, 3, 4], "Сума": column_sums}))
print("Середнє значення масиву:", np.mean(array))

         Стовпець 1  Стовпець 2  Стовпець 3  Стовпець 4
Рядок 1          15           3          14          19
Рядок 2          21          36          15          25
Рядок 3          31          25          42           4
Рядок 4          42          22          26           3

   Рядок  Сума
0      1    51
1      2    97
2      3   102
3      4    93

   Стовпець  Сума
0         1   109
1         2    86
2         3    97
3         4    51

Середнє значення масиву: 21.4375